INSERT IGNORE INTO role(id, name) VALUES(1,'ROLE_USER');
INSERT IGNORE INTO role(id, name) VALUES(2,'ROLE_ADMIN');

INSERT IGNORE INTO Status(id, name) VALUES(1,'CREATING');
INSERT IGNORE INTO Status(id, name) VALUES(2,'IN PROGRESS');
INSERT IGNORE INTO Status(id, name) VALUES(3,'DONE');
